name: Destroy Azure VM by Name

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: "Azure VM Name (e.g., prodyut)"
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init -backend-config="key=${{ github.event.inputs.vm_name }}.tfstate"

    - name: Find Resource Address by VM Name
      id: find_resource
      run: |
        VM_NAME="${{ github.event.inputs.vm_name }}"
        RESOURCE=$(terraform state list | while read addr; do
          if terraform state show "$addr" | grep -q "name *= *\"$VM_NAME\""; then
            echo $addr
            break
          fi
        done)

        if [ -z "$RESOURCE" ]; then
          echo "No matching VM found for name $VM_NAME"
          exit 1
        fi

        echo "Found Terraform resource: $RESOURCE"
        echo "resource=$RESOURCE" >> $GITHUB_OUTPUT

    - name: Terraform Plan Before Destroy
      run: terraform plan -destroy -target=${{ steps.find_resource.outputs.resource }}

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -target=${{ steps.find_resource.outputs.resource }}
