name: Create VM

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: "VM Name"
        required: true
      os_type:
        description: "OS Type"
        required: true
      vm_size:
        description: "VM Size"
        required: true
      os_disk_size:
        description: "OS Disk Size (GB)"
        required: true
      data_disk_size:
        description: "Data Disk Size (GB)"
        required: false



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -backend-config="key=${{ github.event.inputs.vm_name }}.tfstate"
      - name: Set default value for data_disk_size if empty
        run: |
          if [ -z "${{ github.event.inputs.data_disk_size }}" ]; then
            echo "DATA_DISK_SIZE=0" >> $GITHUB_ENV
          else
            echo "DATA_DISK_SIZE=${{ github.event.inputs.data_disk_size }}" >> $GITHUB_ENV
          fi
      - run: terraform apply -auto-approve -var "vm_name=${{ github.event.inputs.vm_name }}" -var "os_type=${{ github.event.inputs.os_type }}" -var "vm_size=${{ github.event.inputs.vm_size }}" -var "os_disk_size=${{ github.event.inputs.os_disk_size }}" -var "data_disk_size=$DATA_DISK_SIZE"

      # - name: Set environment variables
      #   run: |
      #     echo "OS_TYPE=${{ github.event.inputs.os_type }}" >> $GITHUB_ENV
      #     echo "VM_NAME=${{ github.event.inputs.vm_name }}" >> $GITHUB_ENV


      # - name: Push to separate repo
      #   run: |
      #     git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/prodyutguha/vm_tf.git vm-configs
      #     cd vm-configs
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"

      #     if [[ "$OS_TYPE" == *Windows* ]]; then
      #       cp ../windows-vm-${VM_NAME}.tf .
      #       git add windows-vm-${VM_NAME}.tf
      #     else
      #       cp ../linux-vm-${VM_NAME}.tf .
      #       git add linux-vm-${VM_NAME}.tf
      #     fi

      #     git commit -m "Add ${OS_TYPE} VM config for ${VM_NAME}"
      #     git push